/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'generated-index',
        title: 'Getting Started',
        description: 'Get started with tangent',
        slug: '/getting-started',
        keywords: ['getting-started'],
        image: '/img/logo.svg',
      },
      items: ['getting-started/installation', 'getting-started/build-process', 'getting-started/hybrid', 'getting-started/design-tokens', 'getting-started/navigation-menu', 'getting-started/wpcs'],
    },
    {
      type: 'category',
      label: 'Theme.json',
      link: {
        type: 'generated-index',
        title: 'Theme.json',
        description: 'Tangent uses `.jsonc` partials to store all of the theme\'s design settings. These smaller partials are automatically compiled into a `theme.json` file for your theme.',
        slug: '/theme-json',
        keywords: ['theme-json'],
        image: '/img/logo.svg',
      },
      items: ['theme-json/partials', 'theme-json/props'],
    },
    {
      type: 'category',
      label: 'SCSS',
      link: {
        type: 'generated-index',
        title: 'SCSS',
        description: 'Tangent does enqueue stylesheets for the frontend and the block editor, However, Tangent\'s superpowers include the ability to pull props _directly from your theme.json_ as well as generate _block-specific CSS files_ and enqueue them to their specific blocks.',
        slug: '/scss',
        keywords: ['scss'],
        image: '/img/logo.svg',
      },
      items: ['scss/architecture', 'scss/modular', 'scss/breakpoints'],
    },
    {
      type: 'category',
      label: 'Blocks and Block Editor',
      link: {
        type: 'generated-index',
        title: 'Blocks and Block Editor',
        description: 'Get started with tangent',
        slug: '/blocks',
        keywords: ['blocks'],
        image: '/img/logo.svg',
      },
      items: ['blocks/wp-scripts', 'blocks/blocks', 'blocks/block-template-parts'],
    },
    {
      type: 'category',
      label: 'Guides',
      link: {
        type: 'generated-index',
        title: 'Guides',
        description: 'Get started with tangent',
        slug: '/guides',
        keywords: ['guides'],
        image: '/img/logo.svg',
      },
      items: ['guides/adding-a-block'],
    },
    {
      type: 'category',
      label: 'Packages',
      link: {
        type: 'generated-index',
        title: 'Packages',
        description: 'Get started with tangent',
        slug: '/packages',
        keywords: ['packages'],
        image: '/img/logo.svg',
      },
      items: ['packages/json-dir-to-object-loader', 'packages/json-to-scss-loader'],
    },
  ],
};

module.exports = sidebars;
