/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    "intro",
    {
      type: "category",
      label: "Getting Started",
      link: {
        type: "generated-index",
        title: "Getting Started",
        description: "Get started with tangent",
        slug: "/getting-started",
        keywords: ["getting-started"],
        image: "/img/logo.svg",
      },
      items: [
        "getting-started/installation",
        "getting-started/build-process",
        "getting-started/wpcs",
      ],
    },
    {
      type: "category",
      label: "Hybrid Themes and PHP",
      link: {
        type: "generated-index",
        title: "Hybrid Themes and PHP",
        description:
          'Tangent is a "hybrid" theme, meaning that it embraces the block editor and still supports much of the classic PHP-based templating functionality that is sometimes needed. It is built on top of [Underscores](https://underscores.me) and includes a number of features that make it easy to build custom blocks and block patterns, as well as build your styling starting from `theme.json` itself.',
        slug: "/functions-php",
        keywords: ["theme-json"],
        image: "/img/logo.svg",
      },
      items: [
        "functions-php/folder-structure",
        "functions-php/navigation-menu",
      ],
    },
    {
      type: "category",
      label: "Theme.json and SCSS",
      link: {
        type: "generated-index",
        title: "Theme.json and SCSS",
        description:
          "Tangent uses `.jsonc` partials to store all of the theme's design settings. These smaller partials are automatically compiled into a `theme.json` file for your theme. Tangent does enqueue stylesheets for the frontend and the block editor, However, Tangent's superpowers include the ability to pull props _directly from your theme.json_ as well as generate _block-specific CSS files_ and enqueue them to their specific blocks.",
        slug: "/theme-json-scss",
        keywords: ["theme-json"],
        image: "/img/logo.svg",
      },
      items: [
        "theme-json-scss/design-tokens",
        "theme-json-scss/partials",
        "theme-json-scss/architecture",
        "theme-json-scss/props",
        "theme-json-scss/modular",
        "theme-json-scss/breakpoints",
      ],
    },
    {
      type: "category",
      label: "JavaScript and Block Editor",
      link: {
        type: "generated-index",
        title: "JavaScript and Block Editor",
        description: "Get started with tangent",
        slug: "/javascript",
        keywords: ["blocks"],
        image: "/img/logo.svg",
      },
      items: [
        "javascript/wp-scripts",
        "javascript/editor-js",
        "javascript/custom-blocks",
        "javascript/block-template-parts",
      ],
    },
    {
      type: "category",
      label: "Guides",
      link: {
        type: "generated-index",
        title: "Guides",
        description: "Get started with tangent",
        slug: "/guides",
        keywords: ["guides"],
        image: "/img/logo.svg",
      },
      items: ["guides/adding-a-block"],
    },
    {
      type: "category",
      label: "Packages",
      link: {
        type: "generated-index",
        title: "Packages",
        description: "Get started with tangent",
        slug: "/packages",
        keywords: ["packages"],
        image: "/img/logo.svg",
      },
      items: [
        "packages/json-dir-to-object-loader",
        "packages/json-to-scss-loader",
      ],
    },
    "license",
  ],
};

module.exports = sidebars;
